language: node_js

node_js:
  - "6"

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test-only

after_success:
  - npm run typedoc
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    verbose: true
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "nxgrid-*.tgz"
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: npm
    skip_cleanup: true
    email: bacon.josh09@gmail.com
    api_key: $NPM_TOKEN
    on:
      branch: master
      tags: true
