language: node_js


node_js:
  - "6"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/
  github_token: $GITHUB_TOKEN
  on:
    tags: true
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "nxgrid-*.tgz"
  skip_cleanup: true
  on:
    tags: true
deploy:
  provider: npm
  skip_cleanup: true
  email: bacon.josh09@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
